services:

  mysql:
    image: mysql:8
    container_name: inventoryservice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: inventory
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: inventoryservice-rabbit
    ports:
      - "5672:5672"      # for RabbitMQ internal use
      - "15672:15672"    # for management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

volumes:
  mysql_data:
