# docker-compose.yml

version: '3.8'

services:
  inventory:
    build: ./
    ports:
      - "4567:4567"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/flushy_inventory

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
