services:
  inventory:
    build: .
    container_name: inventoryservice-inventory
    ports:
      - "4567:4567"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DB_HOST: mysql
      DB_USER: inventory
      DB_PASSWORD: inventorypass
      DB_NAME: inventorydb
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: pass
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec ruby app.rb

  mysql:
    image: mysql:8
    container_name: inventoryservice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: inventory
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: inventoryservice-rabbit
    ports:
      - "5672:5672"      # for RabbitMQ internal use
      - "15672:15672"    # for management dashboard
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

volumes:
  mysql_data:
